sudo: false
language: node
before_script: ./test/travis-spellcheck.sh
script: bundle exec jekyll build
env:
  global:
    secure: iA6qR597UJQoJEiOJpvaZZQBscc9pRVdIl+k0FxQuubhpfstlPAIaLPzo3TqiKg2y8gL6rvK8J/HCf0VwKQIXDb6y0vOQrYyQSMIP2eorp/y1LvH0LQfRqMM6kEVyimMAM7oxGyLlxRopwGcseXI/vYxr21GiXadlOeK/rkq9Kc=
