sudo: false
language: ruby
rvm: 2.2.0
node_js: stable
before_install:
- git fetch --unshallow
- nvm install stable
install:
- bundle install --without production --deployment
- npm install
cache:
  directories:
  - vendor/bundle
script:
- npm test
- npm run build
after_success:
- bundle exec rake deploy
env:
  global:
  - secure: cIhEBITJHfD+S4KRmefZr7tCZui0Kc3OI+jvSQ8g6X97nqRktucex1fk1hLmVmAx59wJ6QiwJLHHvsNzL49nn0dNQsnIcaw4Y+W7jCkmeHLay7/IZRBtl2W8zOpb51n7eNwNOcQDB3h57788xqF2HtwmDnKHjtPda/9uRnFWuzk=
  - secure: auyKZInzb9e4tIoCUKSCXN2hC2NadO9BlHw+ZRH0OnMAKcOdJ6etVEgxqiQZ6l4/do46cDE4Es7qbmcZunHKYKRbAlJYN5oqM24aWax3SshbtByjTCjiBybdiCTScBoGItjtDDAise0aXq9Y24f8FfSIkv2knTsNahBtk2kc0Ng=
branches:
  except:
  - master
