# Site settings
title: JSer.info
email: info@efcl.info
description: "JavaScriptの最新情報を紹介する週刊ブログ"
keywords:
  - "JavaScript"
  - "ブラウザ"
  - "ECMAScript"
url: "https://jser.info"
baseurl: ""
production_url : "https://jser.info"
github_repo_url : https://github.com/jser/jser.github.io
twitter_username: jser_info
timezone: Asia/Tokyo
encoding: utf-8
exclude:
  - "README.md"
  - "Gemfile"
  - "LICENSE"
  - "bower.json"
  - "import.sh"
  - "package.json"
  - "test/"
  - "vendor"
  - "node_modules"
# Setup
author:
  name: 'azu'
  url:  https://jser.info/
  twitter: azu_re
  github:  azu

paginate: 10
paginate_path: "page/:num"
permalink: /:year/:month/:day/:title/
# Build settings
markdown: redcarpet
# https://github.com/jser/jser.github.io/issues/35
redcarpet:
  extensions: [hard_wrap, with_toc_data]

# collection AMP
collections:
  ampstory:
    output: true

defaults:
  -
    scope:
      path: "_i18n/ja"      # empty string for all files
      type: posts           # limit to posts
    values:
      is_ja_post: true # automatically set is_ja_post=true for all posts

# multiple languages settings
languages: ["ja", "ko"]
exclude_from_localizations: ["bower_components", "node_modules", "public"]

plugins:
  - jekyll-multiple-languages-plugin
  - jekyll-sitemap
  - jemoji
  - jekyll-toc
