# Site settings
title: JSer.info
email: info@efcl.info
description: "JavaScriptの最新情報を紹介する週刊ブログ"
keywords:
  - "JavaScript"
  - "ブラウザ"
  - "ECMAScript"
url: "https://jser.info"
baseurl: ""
production_url : "https://jser.info"
github_repo_url : https://github.com/jser/jser.github.io
twitter_username: jser_info
timezone: Asia/Tokyo
encoding: utf-8
exclude:
  - "README.md"
  - "Gemfile"
  - "LICENSE"
  - "bower.json"
  - "import.sh"
  - "package.json"
  - "test/"
  - "vendor"
  - "node_modules"
# Setup
author:
  name: 'azu'
  url:  https://jser.info/
  twitter: azu_re
  github:  azu

paginate: 10
paginate_path: "page/:num"
permalink: /:year/:month/:day/:title/
# Build settings
markdown: redcarpet
# https://github.com/jser/jser.github.io/issues/35
redcarpet:
  extensions: [hard_wrap, with_toc_data]

# multiple languages settings
languages: ["ja", "ko"]
exclude_from_localizations: ["bower_components", "node_modules", "public"]

gems:
  - jekyll-sitemap
  - jemoji
  - jekyll-toc

# Prose
prose:
  rooturl: '_posts/'
  siteurl: 'https://jser.info'
  media: 'media'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
          type: "text"
      - name: "author"
        field:
          element: "hidden"
          label: "Author"
          value: "azu"
          placeholder: "Trunk Botterson"
          type: "text"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Post Category"
          placeholder: "Create or choose"
          alterable: true
      - name: "tags"
        field:
          element: "multiselect"
          label: "Post Tag"
          placeholder: "Create or choose"
          alterable: true
